name: Redecorating the Soul
favicon: null
layout_spectrum: 0.98625
typography_spectrum: 0.93824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5f1b42'
    - '#ce534e'
    - '#d4d6e2'
    - '#455932'
    - '#90bf70'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
