name: Redecorating the Soul
favicon: null
layout_spectrum: 0.99848
typography_spectrum: 0.93824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cca174'
    - '#996452'
    - '#e2c4a0'
    - '#434128'
    - '#16110b'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
