name: Redecorating the Soul
favicon: null
layout_spectrum: 0.5293892186600715
typography_spectrum: 0.93824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a00000'
    - '#000012'
    - '#8db883'
    - '#1a54a6'
    - '#99531f'
  brandStrength: 0.6768123405054212
  lightness: 0.3841691263951361
  saturation: 0.8580211580265313
  rhythmicContrast: 0.6511636190116405
purpose: []
